type = "checkout_ui_extension"
name = "my-checkout-ui-extension"

extension_points = [
  'Checkout::Dynamic::Render'
]

[[metafields]]
namespace = "my-namespace"
key = "my-key"

[[metafields]]
namespace = "my-namespace"
key = "my-key-2"

[capabilities]
network_access = true
block_progress = true
api_access = true

[settings]
  [[settings.fields]]
  key = "banner_title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner"

  [[settings.fields]]
  key = "field_key"
  type = "boolean"
  name = "field-name"
  [[settings.fields]]
  key = "field_key_2"
  type = "number_integer"
  name = "field-name-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration